# coding: utf8

def index(): return plugin_flatpage()
def about(): return plugin_flatpage()
def venue(): return plugin_flatpage()
def maps(): return plugin_flatpage()
def schedule(): return plugin_flatpage()
def proposals(): return plugin_flatpage()
def lightning(): return plugin_flatpage()
def keynotes(): return plugin_flatpage()
def openspace(): return plugin_flatpage()
def tutorials(): return plugin_flatpage()
def workshops(): return plugin_flatpage()
def sprints(): return plugin_flatpage()
def extreme(): return plugin_flatpage()
def posters(): return plugin_flatpage()
def staff(): return plugin_flatpage()
def volunteer(): return plugin_flatpage()
def fa(): return plugin_flatpage()
