# coding: utf8

def index(): return plugin_flatpage()
def about(): return plugin_flatpage()
def venue(): redirect(URL(c="venue", f="index", vars=request.vars))
def maps(): redirect(URL(c="venue", f="maps", vars=request.vars))
def schedule(): return plugin_flatpage()
def proposals(): return plugin_flatpage()
def lightning(): return plugin_flatpage()
def keynotes(): return plugin_flatpage()
def openspace(): return plugin_flatpage()
def tutorials(): return plugin_flatpage()
def workshops(): return plugin_flatpage()
def sprints(): return plugin_flatpage()
def summits(): return plugin_flatpage()
def extreme(): return plugin_flatpage()
def posters(): return plugin_flatpage()
def staff(): return plugin_flatpage()
def volunteer(): return plugin_flatpage()
def diversity(): return plugin_flatpage()
def fa(): return plugin_flatpage()
def registration(): return plugin_flatpage()
def diversity(): return plugin_flatpage()
def summit(): return plugin_flatpage()
