body_template="""
Your Financial Aid Application has been %s.
Thank you; your updates will be reviewed.

Time:     %s
  Name:        %s %s [#%s]
  Address:     %s 
               %s
               %s, %s %s (%s)
  Email:       %s


APPLICATION:
  Registration Type:          %s
  Registration Amount:        $ %4.2f
  
  Number Nights:              %d
  Total Lodging Amount:       $ %4.2f
  Roommates:                  %s

 
TRANSPORTATION:
%s

  Transportation Amount:     $ %4.2f
  
TOTAL REQUEST:           $ %5.2f
Minimum Reguest:         $ %5.2f

RATIONALE:
%s

(This email was automatically generated by PyCon2009 Registration System)
"""
 
def email_fa(mode):
    fa=db(db.fa.person==auth.user.id).select()[0]
    person=db(db.auth_user.id==auth.user.id).select()[0]
    body=body_template % (mode, fa.modified_on,
                          person.first_name,person.last_name,person.id,
                          person.address1,person.address2,person.city,person.state,person.zip_code,person.country,
                          person.email,
                          person.attendee_type,
                          fa.registration_amount, fa.hotel_nights, fa.total_lodging_amount, fa.roommates,
                          fa.transportation_details, fa.transportation_amount,
                          fa.total_amount_requested, fa.minimum_amount_requested,
                          fa.rationale
                          )
    if DEV_TEST:  # careful!  I've only just printed this to console, so only use for local testing
        # you could add this:
        # if request.env.http_host == '127.0.0.1:8000'
        # or... output to the screen....
        # response.headers['Content-Type']='text/plain'
        # return str("t2.email(\n"+EMAIL_SENDER+"["+FA_EMAIL_TO+person.email+"]"+"\nsubject="+'PyCon FA Application Updated [#%s]' % fa.id+body+"\n)")
        print "t2.email(\n",EMAIL_SENDER,[FA_EMAIL_TO,person.email],"\nsubject=",'PyCon FA Application Updated [#%s]' % fa.id,body,")"
    else:
        mail.send(to=[FA_EMAIL_TO,person.email],
                  subject='Financial Aid Application Updated [#%s]' % fa.id,
                  message=body)

def email_fa_select(query=db.fa.id>0):
    for fa in db(query).select():
        person=db(db.auth_user.id==fa.person).select()[0]
        body=body_template % ("retrieved by a manager", fa.modified_on,
                              person.first_name,person.last_name,person.id,
                              person.address1,person.address2,person.city,person.state,person.zip_code,person.country,
                              person.email,
                              person.attendee_type,
                              fa.registration_amount, fa.hotel_nights, fa.total_lodging_amount, fa.roommates,
                              fa.transportation_details, fa.transportation_amount,
                              fa.total_amount_requested, fa.minimum_amount_requested,
                              fa.rationale
                              )
        if DEV_TEST:  # careful!  I've only just printed this to console, so only use for local testing
            # you could add this:
            # if request.env.http_host == '127.0.0.1:8000'
            # or... output to the screen....
            # response.headers['Content-Type']='text/plain'
            # return str("t2.email(\n"+EMAIL_SENDER+"["+FA_EMAIL_TO+"]"+"\nsubject="+'PyCon FA Application Updated [#%s]' % fa.id+ body+ "\n)")
            print "t2.email(\n",EMAIL_SENDER,[FA_EMAIL_TO],"\nsubject=",'PyCon FA Application Updated [#%s]' % fa.id, body, ")"
        else:
            t2.email(EMAIL_SENDER,[FA_EMAIL_TO],subject='PyCon FA Application Updated [#%s]' % fa.id, message=body)

